# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"instance_sort": "00_core.ipynb",
         "instance_dcmread": "00_core.ipynb",
         "instance_show": "00_core.ipynb",
         "get_dicom_image": "00_core.ipynb",
         "mask_and_save": "00_core.ipynb",
         "DcmDataset.updated_dict": "00_core.ipynb",
         "pd.DataFrame.from_dicoms2": "00_core.ipynb",
         "dicom_convert_3channel": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/fmi/"

git_url = "https://github.com/fastai/fmi/tree/master/"

def custom_doc_links(name): return None
