# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"system_info": "02_explore.ipynb",
         "random_": "02_explore.ipynb",
         "get_image_info": "02_explore.ipynb",
         "get_pii": "02_explore.ipynb",
         "instance_sort": "02_explore.ipynb",
         "instance_dcmread": "02_explore.ipynb",
         "instance_show": "02_explore.ipynb",
         "scaled_px": "02_explore.ipynb",
         "DcmDataset.show": "02_explore.ipynb",
         "get_dicom_image": "02_explore.ipynb",
         "dicom_convert_3channel": "02_explore.ipynb",
         "show_aspects": "02_explore.ipynb",
         "mask_and_save_path": "03_preprocessing.ipynb",
         "mask_and_save_df": "03_preprocessing.ipynb",
         "image_hist": "03_preprocessing.ipynb",
         "move_files": "03_preprocessing.ipynb",
         "dicomsplit": "03_preprocessing.ipynb",
         "check_duplicate": "03_preprocessing.ipynb",
         "dicom_splitter": "03_preprocessing.ipynb",
         "dicom_windows": "04_pipeline.ipynb",
         "PILWindow": "04_pipeline.ipynb",
         "LungWindow": "04_pipeline.ipynb",
         "PEWindow": "04_pipeline.ipynb"}

modules = ["explore.py",
           "preprocessing.py",
           "pipeline.py"]

doc_url = "https://asvcode.github.io/fmi/"

git_url = "https://github.com/asvcode/fmi/tree/master/"

def custom_doc_links(name): return None
