# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00a_preprocessing.ipynb (unless otherwise specified).

__all__ = ['instance_sort']

# Cell
from fastai.vision.all import *
from fastai.medical.imaging import *
from torchvision.utils import save_image

# Cell
def instance_sort(folder:(Path, L)):
    "sort files by instance number"
    if isinstance(folder, Path): folder = get_dicom_files(folder)
    if isinstance(folder, L): folder = folder
    sorted_files = []
    for file in folder:
        instance = dcmread(file)[0x20, 0x13].value
        sorted_files.append([instance, file])
    return L(sorted(sorted_files))