# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_train.ipynb (unless otherwise specified).

__all__ = ['EpochIteration']

# Cell
from fastai.vision.all import *
from timm import create_model
from fastai.vision.learner import _update_first_layer

# Cell
class EpochIteration(Callback):
    "Display Epoch and Iteration with option to display images"
    def __init__(self, show_img=False):
        self.show_img = show_img
    def before_batch(self):
        if self.training is not False:
            b = f'Training: Epoch: {self.epoch} Iter: {self.iter} Loss:{self.loss}'
        else:
            b = f'Validation: Epoch: {self.epoch} Iter: {self.iter} Loss:{self.loss}'

        if self.show_img is not False:
            show_images(self.learn.xb[0], suptitle=b)
        else:
            print(b)